[package]
name = "josephus1"
version = "0.1.0"
edition = "2018"

[features]
debug = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
